title: Personal Page
url: "https://shiqiu0419.github.io/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: <script type="text/javascript" id="clustrmaps" src="//cdn.clustrmaps.com/map_v2.js?d=V7D6ej10gXXtCoqISuoasXbDtklVb6oGJd8AjiUwY58&cl=ffffff&w=a"></script>

footer: yes
footer_text: "Page maintained by Shi Qiu"

sass:
    style: compressed
    sass_dir: _sass

