title: Researcher
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page maintained by Shi Qiu"

sass:
    style: compressed
    sass_dir: _sass

