title: Personal Page
url: "https://shiqiu041911.github.io/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page maintained by Shi Qiu"

sass:
    style: compressed
    sass_dir: _sass

